### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by Er-rchydy** [fantasy525/react-native-crosswalk-webview-plus#2]
Can you add please a section explaining how to use this. or we can just import `WebView` from `react-native` and it will automatically use  crosswalk webview instead of the original one

**Comment by fantasy525** [comment]
> Can you add please a section explaining how to use this. or we can just import `WebView` from `react-native` and it will automatically use crosswalk webview instead of the original one

hello，and you can read readme,You should configure android dependencies manually,and I will update readme in English.
you cant't import WebView from 'react-native',you should import my WebView Components so that rn will use crosswalkWebview

**Comment by Er-rchydy** [comment]
ok thanks
