### ISSUE TITLE
fullscreen is not working

### ISSUE THREAD

**Issue by Er-rchydy** [fantasy525/react-native-crosswalk-webview-plus#3]
I have a video player in the page, and i want to view it in a fullscreen. 
currently when i click on fullscreen, the player take 100% of the  height i gave to`CrosswalkWebview`, is there an option to make it takes the phone height?

**Comment by fantasy525** [comment]
If you want the webview to hold up to the height of the phone，you can set webview style,example:
```javascript
const {width,height} = Dimensions.get('window');
import { RCTCrossWalkWebView } from 'react-native-crosswalk-webview-plus'
...
<View style={{widht:width,height:height}}>
 <RCTCrossWalkWebView
       source={ { uri:'http://xxx.com'}}
      />
</View
```

**Comment by fantasy525** [comment]
> I have a video player in the page, and i want to view it in a fullscreen.
> currently when i click on fullscreen, the player take 100% of the height i gave to`CrosswalkWebview`, is there an option to make it takes the phone height?

If it's not work,show me your codes.

**Comment by Er-rchydy** [comment]
@fantasy525 when i import `RCTCrossWalkWebView` the way you did, it's not working at all 
```
import { RCTCrossWalkWebView } from 'react-native-crosswalk-webview-plus' // didn't work
import  RCTCrossWalkWebView  from 'react-native-crosswalk-webview-plus' // did work
```

i'm not sure you understood the issue.
i don't want the webView to hold up to the height of the phone, i want it to be just like 500px, what i want to hold up to the height of the phone is the VIDEO PLAYER that exist inside the webView, like you already know all video players has a fullscreen button, when you click that fullscreen button the video player takes the whole phone screen. and when you exit that fullscreen the video player got smaller. 
so the problem her is the webView is blocking the video player to take the fullscreen. for example if the webView height is 500px and the height of the video player is 200px, when i click the fullscreen button the video player got only 500px ( the height of the  webView), if was 300px, the video player get only 300px in fullscreen.

**Comment by fantasy525** [comment]
> @fantasy525 when i import `RCTCrossWalkWebView` the way you did, it's not working at all
> 
> ```
> import { RCTCrossWalkWebView } from 'react-native-crosswalk-webview-plus' // didn't work
> import  RCTCrossWalkWebView  from 'react-native-crosswalk-webview-plus' // did work
> ```
> i'm not sure you understood the issue.
> i don't want the webView to hold up to the height of the phone, i want it to be just like 500px, what i want to hold up to the height of the phone is the VIDEO PLAYER that exist inside the webView, like you already know all video players has a fullscreen button, when you click that fullscreen button the video player takes the whole phone screen. and when you exit that fullscreen the video player got smaller.
> so the problem her is the webView is blocking the video player to take the fullscreen. for example if the webView height is 500px and the height of the video player is 200px, when i click the fullscreen button the video player got only 500px ( the height of the webView), if was 300px, the video player get only 300px in fullscreen.

sorry，that's my fault , and I update it ,now you can 
```javascript
import { RCTCrossWalkWebView } from 'react-native-crosswalk-webview-plus'
```
you can see my git commits log,
and now I understand you issue,I think the reason video doesn't play in full screen is because it's limited by the height of the webview，I think when you click the full screen button you can send a message to react-native's component and then change the height of the webview by calling setNativeProps.

**Comment by Er-rchydy** [comment]
ok thanks
