### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by ghostknow** [fantasy525/react-native-crosswalk-webview-plus#6]
How to solve Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined problem?
Thanks

**Comment by fantasy525** [comment]
@ghostknow Hi ,I have fixed the bug,can you try it?
I resolve this:
index.js
```
-import RCTCrossWalkWebView from './RCTCrossWalkWebView'  // delete                                             
+import {RCTCrossWalkWebView} from './RCTCrossWalkWebView'  // add                                    

```

**Comment by fantasy525** [comment]
@ghostknow I’m sorry,I dont' have time to test it,It seems like a small bug,you can test it?thanks!
