### ISSUE TITLE
Control caching by url / extension

### ISSUE THREAD

**Issue by dgoenka** [fantasy525/react-native-crosswalk-webview-plus#7]
Hi, I'm trying out this Crosswalk WebView implementation and apart from some problems from listeners (which I'm sure I can manage) its all going well. 

However, there is one problem for which I'm unable to proceed. This WebView is caching html's and uses stale versions when it should not (in my app). I appreciate caching for most other types of resources (Images, JS, CSS, Fonts, etc) and want to cache these extensions. Is there way to / do you plan on adding a way to control the caching?

**Comment by fantasy525** [comment]
you want to cache img,js,css but html? if true,you can do this to test:
1. 
```
// CrosswalkWebViewGroupManager.java ,line 74
settings.setCacheMode(XWalkSettings.LOAD_DEFAULT); // set default mode
```
and webview will base on cache-control to cache resources.
